// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bc_dteDUXfyqHgh4WfBYC8TCVyh067k',
    appId: '1:212482961943:web:ec0f56ca859561bdcf2252',
    messagingSenderId: '212482961943',
    projectId: 'device-streaming-992f8680',
    authDomain: 'device-streaming-992f8680.firebaseapp.com',
    storageBucket: 'device-streaming-992f8680.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1CH9uXJUdXWISCk0aitZXuyvZv2yXO5Y',
    appId: '1:212482961943:android:48e590e27ce858a9cf2252',
    messagingSenderId: '212482961943',
    projectId: 'device-streaming-992f8680',
    storageBucket: 'device-streaming-992f8680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABY8kBmE6i4bFjc2Jy1WzJ720w_Sl-MXM',
    appId: '1:212482961943:ios:5de525fe53912f4acf2252',
    messagingSenderId: '212482961943',
    projectId: 'device-streaming-992f8680',
    storageBucket: 'device-streaming-992f8680.firebasestorage.app',
    iosBundleId: 'com.example.apiIntegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABY8kBmE6i4bFjc2Jy1WzJ720w_Sl-MXM',
    appId: '1:212482961943:ios:09464955b80a5bd3cf2252',
    messagingSenderId: '212482961943',
    projectId: 'device-streaming-992f8680',
    storageBucket: 'device-streaming-992f8680.firebasestorage.app',
    iosBundleId: 'com.example.apiIntegration.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8bc_dteDUXfyqHgh4WfBYC8TCVyh067k',
    appId: '1:212482961943:web:d6d8de2f64653ddfcf2252',
    messagingSenderId: '212482961943',
    projectId: 'device-streaming-992f8680',
    authDomain: 'device-streaming-992f8680.firebaseapp.com',
    storageBucket: 'device-streaming-992f8680.firebasestorage.app',
  );
}
